test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudinary:
  service: Cloudinary
  folder: ecommerce
  cloud_name: <%= ENV['CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUD_API_KEY'] %>
  api_secret: <%= ENV['CLOUD_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false
